# Generated by Django 5.1.2 on 2024-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "administratorID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=10, unique=True)),
                ("password", models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
