# Generated by Django 5.1.2 on 2024-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_administrator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Administrator",
        ),
        migrations.AddField(
            model_name="user",
            name="isAdmin",
            field=models.BooleanField(default=False),
        ),
    ]
