# Generated by Django 5.1.2 on 2024-12-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_delete_administrator_user_isadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
