# Generated by Django 5.1.2 on 2024-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_user_last_login_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
