# Generated by Django 5.1.2 on 2024-12-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0007_user_last_login_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
