# Generated by Django 5.1.2 on 2024-12-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0008_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="VIPPrice",
        ),
        migrations.RemoveField(
            model_name="price",
            name="basePrice",
        ),
    ]
