# Generated by Django 5.1.2 on 2024-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0009_remove_price_vipprice_remove_price_baseprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="price",
            name="type",
            field=models.CharField(default="Base", max_length=100),
        ),
    ]
