# Generated by Django 5.1.2 on 2024-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0010_price_price_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
